apiVersion: v1
kind: List
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: openshift-applier-operator
    name: openshift-applier-operator
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: openshift-applier-operator
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: openshift-applier-operator
    name: openshift-applier-operator
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: openshift-applier-operator
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: openshift-applier-operator
    labels:
      app: openshift-applier-operator
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: openshift-applier-operator
    template:
      metadata:
        labels:
          name: openshift-applier-operator
      spec:
        serviceAccountName: openshift-applier-operator
        containers:
          - name: openshift-applier-operator
            image: openshift-applier-operator:latest
            ports:
            - containerPort: 60000
              name: metrics
            - containerPort: 3000
              name: http
            imagePullPolicy: Always
            env:
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: OPERATOR_NAME
                value: "openshift-applier-operator"
